// givesachat-cloudflare/src/odyseeEmotes.js

/* ---------------------------------------------------------
   Odysee custom emote manifest  (the "48 px" set)

   GENERATED by evaluating Odysee's own emote module rather than
   transcribed by hand, so these paths are exact:

     const url  = (p) => `https://static.odycdn.com/emoticons/${p}`;
     const E    = (name, path) => ({ name: `:${name}:`, url: url(path) });
     const set  = (dir, suffix) => [ E("sleep", `${dir}/Sleep${suffix}.png`), ... ];
     const emotes = set("48%20px", "%402x");

   The client builds four size variants — 24 px, 36px, 48 px and
   72 px, with suffixes "", "@1.5x", "@2x" and "@3x" — but only
   the 48/@2x set is exported for chat. That is why every custom
   emote is a @2x file.

   THE TOKEN IS NOT THE FILENAME. There is no rule connecting
   them; the mapping is arbitrary and had to come from the
   source:

     :sleep:       Sleep@2x.png       capitalised
     :rock:        ROCK@2x.png        upper-cased
     :cry_1:       cry@2x.png         suffix means "first cry"
     :cry_2:       cry 2@2x.png       ...not a size variant
     :confused_2:  confused@2x.png    but _2 here means the base
     :confused_1:  confused@2x-1.png  and _1 means the "-1" file
     :what:        what_@2x.png       trailing underscore
     :woodoo_doll: woodo doll@2x.png  misspelt on their CDN
     :space_doge:  doge@2x.png        prefix dropped entirely

   Spaces are percent-encoded. One entry in their source uses a
   literal space where the others use %20 — normalised here,
   since a browser encodes it either way.

   80 emotes. A token not in this list falls through to
   OdyseeRoom's twemoji probing, so a newly added emote degrades
   to guess-and-check rather than to nothing.
--------------------------------------------------------- */

const CDN = "https://static.odycdn.com/emoticons/";

const CUSTOM = {
  alien:                  "48%20px/Alien%402x.png",
  angry_1:                "48%20px/angry%402x.png",
  angry_2:                "48%20px/angry%202%402x.png",
  angry_3:                "48%20px/angry%203%402x.png",
  angry_4:                "48%20px/angry%204%402x.png",
  blind:                  "48%20px/blind%402x.png",
  block:                  "48%20px/block%402x.png",
  bomb:                   "48%20px/bomb%402x.png",
  brain_chip:             "48%20px/Brain%20chip%402x.png",
  confirm:                "48%20px/CONFIRM%402x.png",
  confused_1:             "48%20px/confused%402x-1.png",
  confused_2:             "48%20px/confused%402x.png",
  cooking_something_nice: "48%20px/cooking%20something%20nice%402x.png",
  cry_1:                  "48%20px/cry%402x.png",
  cry_2:                  "48%20px/cry%202%402x.png",
  cry_3:                  "48%20px/cry%203%402x.png",
  cry_4:                  "48%20px/cry%204%402x.png",
  cry_5:                  "48%20px/cry%205%402x.png",
  donut:                  "48%20px/donut%402x.png",
  eggplant:               "48%20px/eggplant%402x.png",
  eggplant_with_condom:   "48%20px/eggplant%20with%20condom%402x.png",
  fire_up:                "48%20px/fire%20up%402x.png",
  flat_earth:             "48%20px/Flat%20earth%402x.png",
  flying_saucer:          "48%20px/Flying%20saucer%402x.png",
  heart_chopper:          "48%20px/heart%20chopper%402x.png",
  hyper_troll:            "48%20px/HyperTroll%402x.png",
  ice_cream:              "48%20px/ice%20cream%402x.png",
  idk:                    "48%20px/IDK%402x.png",
  illuminati_1:           "48%20px/Illuminati%402x-1.png",
  illuminati_2:           "48%20px/Illuminati%402x.png",
  kiss_1:                 "48%20px/kiss%402x.png",
  kiss_2:                 "48%20px/kiss%202%402x.png",
  laser_gun:              "48%20px/laser%20gun%402x.png",
  laughing_1:             "48%20px/Laughing%402x.png",
  laughing_2:             "48%20px/Laughing%202%402x.png",
  lollipop:               "48%20px/Lollipop%402x.png",
  love_1:                 "48%20px/Love%402x.png",
  love_2:                 "48%20px/Love%202%402x.png",
  monster:                "48%20px/Monster%402x.png",
  mushroom:               "48%20px/mushroom%402x.png",
  nail_it:                "48%20px/Nail%20It%402x.png",
  no:                     "48%20px/NO%402x.png",
  ouch:                   "48%20px/ouch%402x.png",
  peace:                  "48%20px/peace%402x.png",
  pizza:                  "48%20px/pizza%402x.png",
  rabbit_hole:            "48%20px/rabbit%20hole%402x.png",
  rainbow_puke_1:         "48%20px/rainbow%20puke%402x-1.png",
  rainbow_puke_2:         "48%20px/rainbow%20puke%402x.png",
  rock:                   "48%20px/ROCK%402x.png",
  sad:                    "48%20px/sad%402x.png",
  salty:                  "48%20px/salty%402x.png",
  scary:                  "48%20px/scary%402x.png",
  sleep:                  "48%20px/Sleep%402x.png",
  slime_down:             "48%20px/slime%20down%402x.png",
  smelly_socks:           "48%20px/smelly%20socks%402x.png",
  smile_1:                "48%20px/smile%402x.png",
  smile_2:                "48%20px/smile%202%402x.png",
  space_chad:             "48%20px/space%20chad%402x.png",
  space_doge:             "48%20px/doge%402x.png",
  space_green_wojak:      "48%20px/space%20wojak%402x-1.png",
  space_julian:           "48%20px/Space%20Julian%402x.png",
  space_red_wojak:        "48%20px/space%20wojak%402x.png",
  space_resitas:          "48%20px/resitas%402x.png",
  space_tom:              "48%20px/space%20Tom%402x.png",
  spock:                  "48%20px/SPOCK%402x.png",
  star:                   "48%20px/Star%402x.png",
  sunny_day:              "48%20px/sunny%20day%402x.png",
  surprised:              "48%20px/surprised%402x.png",
  sweet:                  "48%20px/sweet%402x.png",
  thinking_1:             "48%20px/thinking%402x-1.png",
  thinking_2:             "48%20px/thinking%402x.png",
  thumb_down:             "48%20px/thumb%20down%402x.png",
  thumb_up_1:             "48%20px/thumb%20up%402x-1.png",
  thumb_up_2:             "48%20px/thumb%20up%402x.png",
  tinfoil_hat:            "48%20px/tin%20hat%402x.png",
  troll_king:             "48%20px/Troll%20king%402x.png",
  ufo:                    "48%20px/ufo%402x.png",
  waiting:                "48%20px/waiting%402x.png",
  what:                   "48%20px/what_%402x.png",
  woodoo_doll:            "48%20px/woodo%20doll%402x.png"
};

/**
 * @param {string} name  a :token: with the colons stripped
 * @returns {{kind:"emote", url:string}|null}
 */
export function odyseeCustomEmote(name) {
  const path = CUSTOM[name];
  return path ? { kind: "emote", url: CDN + path } : null;
}

export const ODYSEE_CUSTOM_EMOTE_COUNT = 80;
